addons:
  ssh_known_hosts: ssh.cs.kuleuven.be

env:
  - SERVER=ssh.cs.kuleuven.be
script:
  - binaries/hugo

# https://oncletom.io/2016/travis-ssh-deploy/#comments
# problem: At ssh-add /tmp/deploy_rsa I get asked a passphrase.
# same @ https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md
# attempt 3: https://semantic-release.gitbook.io/semantic-release/recipes/git-hosted-services/git-auth-ssh-keys
before_install:
  # Decrypt the git_deploy_key.enc key into /tmp/ folder  
  - openssl aes-256-cbc -K $encrypted_110302702255_key -iv $encrypted_110302702255_iv 
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  # Make sure only the current user can read the private key
  - chmod 600 /tmp/deploy_rsa
  # Create a script to return the passphrase environment variable to ssh-add
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  # Start the authentication agent
  - eval "$(ssh-agent -s)"
  # Add the key to the authentication agent
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/deploy_rsa </dev/null

deploy:
  provider: script
  skip_cleanup: true
  script:
    #- rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/docs ${SSH_USERNAME}@$SERVER:/home/${SSH_USERNAME}/
    #- scp dist/* ${SSH_USERNAME}@$SERVER:/home/${SSH_USERNAME}
    - tar czf - public_html/* | ssh ${SSH_USERNAME}@$SERVER 'cd /cw/vwww/ovi && sg oviwwwg "tar xzvf -"'
  on:
    branch: master
