addons:
  ssh_known_hosts: ssh.cs.kuleuven.be

env:
  - SERVER=ssh.cs.kuleuven.be
script:
  - binaries/hugo

before_install:
  - openssl aes-256-cbc -K $encrypted_110302702255_key -iv $encrypted_110302702255_iv 
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/docs woutergr@$SERVER:/home/wouterg/
  on:
    branch: master
