addons:
  ssh_known_hosts: ssh.cs.kuleuven.be

env:
  - SERVER=ssh.cs.kuleuven.be
script:
  - binaries/hugo

# https://oncletom.io/2016/travis-ssh-deploy/#comments
# problem: At ssh-add /tmp/deploy_rsa I get asked a passphrase.
# same @ https://github.com/dwyl/learn-travis/blob/master/encrypted-ssh-keys-deployment.md
before_install:
  - openssl aes-256-cbc -K $encrypted_110302702255_key -iv $encrypted_110302702255_iv 
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - echo -e "Host $SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Create a script to return the passphrase environment variable to ssh-add
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  #- ssh-add /tmp/deploy_rsa
  # Add the key to the authentication agent
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/deploy_rsa </dev/null

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/docs woutergr@$SERVER:/home/wouterg/
  on:
    branch: master
