addons:
  ssh_known_hosts: ssh.cs.kuleuven.be

script:
  - binaries/hugo

before_install:
  - openssl aes-256-cbc -K $encrypted_110302702255_key -iv $encrypted_110302702255_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
